### ISSUE TITLE
Support TV webos

### ISSUE THREAD

**Issue by pepsonEL** [ollo69/ha-smartthinq-sensors#140]
Hi
Is any chance to add support for webos TV ? I have old model with webos 2.0 and i have added it to app on android LG ThinQ but in integration i dont see it. Only see washer and fridge.

**Comment by ollo69** [comment]
There is a [native dedicated integration](https://www.home-assistant.io/integrations/webostv/) in HA for this.

**Comment by RobertusIT** [comment]
> There is a [native dedicated integration](https://www.home-assistant.io/integrations/webostv/) in HA for this.


Isn't the same.

You can only switch input.

With lg thinq you can change volume, channel, turn on off etc... 

So if is possible, need it

**Comment by ollo69** [comment]
Honestly I have no idea how communication between ThinQ App and TV are implemented, and I don't have a LG TV to analyze this. So I'm not able to this until someone with a LG TV will capture the command "sniffing" the network with a tool as [mitmiproxy](https://mitmproxy.org/).
For the moment I close this thread because there are no possibility to implement your request, come back here or open a new one if you have additional information.
