### ISSUE TITLE
Swing-modus [Feature Request]

### ISSUE THREAD

**Issue by RedWheiler80** [ollo69/ha-smartthinq-sensors#160]
It would be great to get the ability to choose swing-modes for aircon. 

At this moment I'm using 2 integrations for my 2 LG aircons, cause the lack of this feature, would be nice to get rid of the other integration.

**Comment by ollo69** [comment]
Please can you be more specific? Vertical swing should be support, you don't have this option available?

**Comment by RedWheiler80** [comment]
Vertical swing-modes should be nice also :)

**Comment by RedWheiler80** [comment]
I know nothing about Python, but this is what I find at the other integration for swingmodes:

`def swing_modes_index():
    from wideq import ACHSwingMode, ACVSwingMode

    # name: [horz_key, vert_key]
    return {
        "Off": [ACHSwingMode.OFF, ACVSwingMode.OFF],
        "Vertical": [ACHSwingMode.OFF, ACVSwingMode.ALL],
        "Horizontal": [ACHSwingMode.ALL, ACVSwingMode.OFF],
        "Up Left": [ACHSwingMode.FIVE, ACVSwingMode.ONE],
        "Up Right": [ACHSwingMode.ONE, ACVSwingMode.ONE],
        "Up": [ACHSwingMode.ALL, ACVSwingMode.ONE],
    }`

Like this it's easy to add your own modes into that file:


```
        "Normal": [ACHSwingMode.ALL, ACVSwingMode.TWO],
        "Special": [ACHSwingMode.FIVE, ACVSwingMode.FOUR],
```

**Comment by ollo69** [comment]
Related to swing modes the story is a little bit more complex. 
AC device normally manage Vertical and Horizontal swing, that are totally independent. Combination of all swing modes is very big, and because HA at this moment only support 1 swing mode option it is not possible to include all.
In the example above (that come from other integration) someone choose in an arbitrary way  to define some combination. It may be good for someone, bad for other.
My approach is a little bit different. I started managing only Vertical swing, and the idea is to introduce Horizontal swing in the future with a dedicated service, so that it will be possible to define all possible combination.
There is also a proposed change in HA to add a new standard option in climate entity to manage Horizontal Swing, but I don't know how long this change will take to be implemented.

So my first question is: does vertical swing work properly for your device with the integration? Are you able to activate all possible vertical options?

**Comment by RedWheiler80** [comment]
Thank you for your answer.

I can confirm I can use every swing mode that I want with this (but, there are 5 standard modes, and if you need more you just add them like my second example). I'm using that integration for a while without problems. Now I stumbled on this integration while looking for another solution for my new (duct-unit) device. Cause the other integration won't show any of the temperatures for that device.

But at the moment I'm just using both integrations and have all the benefits for my both devices.

Thanks again.

**Comment by ollo69** [comment]
I think you don't understand my sentence and my question. The code above is not applicable on this integration, because this are a subset of all available combination of vert + horiz swing. I used a total different approach, that better respect the HA architecture. I'd like to know if the vertical swing mode currently available in this integration work with your device, horizontal will come later...

**Comment by RedWheiler80** [comment]
Yes, I can confirm the vertical swing mode from your integration does the job excellent over here.

I'll close this request and will wait for an update. Thank you in advance, and also for all the neat work you did already with this integration!
