### ISSUE TITLE
Icon color when using homekit integration

### ISSUE THREAD

**Issue by Y8rz8** [ollo69/ha-smartthinq-sensors#178]
Hi there,

First thanks for this plugin which is working perfectly for my LG air conditioners.

I’m using the homekit integration (bridge) and devices are well recognized in HomeKit but the icon color don’t change. It stays in green (which means standby) whereas it should be in blue (meaning cool) or in orange (meaning hot). 
I don’t know if this is related to the plugin or to the homekit integration for climate devices.
Any idea ?

Thanks,
Patrice.

**Comment by ollo69** [comment]
Really know nothing about HomeKit and if there are something that integration should do to provide this information.
If you can provide additional detail on possible requirement.

**Comment by Y8rz8** [comment]
This is in the HomeKit API for developer. Page 174 there is the information on « current heater cooler state » with several value inactive, idle, heating, cooling. Corresponding colors are grey, green, orange, blue.
But I guess this is more a topic for the HomeKit integration component. I will try on this side.

**Comment by Y8rz8** [comment]
I have received the answer from the owner of HomeKit integration in HA:

_The Home Assistant entity must implement https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action for this to work._

If it can help.

**Comment by ollo69** [comment]
Added HVAC Action in last release.

**Comment by Y8rz8** [comment]
That was quick 👍 Thanks !
I have done some tests this morning but the issue seems still there.
I will do some other tests by changing status (and try some combinations) and will keep you posted.

**Comment by ollo69** [comment]
At this moment I have implemented HVAC Action in integration, but probably I will roll-back this change shortly. I had some discussion with HA core team, and the HVAC action property should be implemented only to provide information of what climate device is doing if this can be different from the HVAC mode (e.g, the HVAC mode is cool but the current action is idle). You can find more detail about this property [here](https://developers.home-assistant.io/docs/core/entity/climate#hvac-action) LG protocol is not possible to identify this condition and so implement HVAC action does not make sense because is just the same od HVAC mode. I think that this issue should be addressed in HomeKit integration, that should use HVAC mode if HVAC action is not available (this is true for many climate integration).

**Comment by Y8rz8** [comment]
Thx for your feedback and understood !
