### ISSUE TITLE
[BUG] Washer "Remain time" stops at 0:01

### ISSUE THREAD

**Issue by JonathanTroyer** [ollo69/ha-smartthinq-sensors#198]
**Describe the bug**
`sensor.washer` shows that it's completed, but `remain_time` is stuck at 0:01

**Expected behavior**
When the washer completes and `binary_sensor.washer_wash_completed` is set to `on`, then `remain_time` should be 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/15098499/130309807-cac3a74d-91f6-41c7-a30c-9848e2bedffb.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspberry Pi 3 B+
 - Home Assistant version installed: core-2021.8.6
 - Component version installed: v0.8.20
 - Last know working version: N/A
 - LG device type and model with issue:
 - LG devices connected (list):
   - F3L7CYK5W_US_WIFI-FL (WASHER)
   - RV13B6ES_D_US_WIFI-Dryer (DRYER)

**Output of HA logs**
```
N/A
```

**Additional context**
Note that this does not happen for the dryer. My best guess is that this is happening because the washer is turning off before it reports an updated remaining time.

For the time being, I'm just using a conditional card to show/hide the status based on the completion state, which works effectively.

**Comment by ollo69** [comment]
Sorry for late answer. If problem still there, could you please try using last released version and than report here results and HA logs? Thanks.

**Comment by ollo69** [comment]
Please attach diagnostic (available from last release) extracted when problems occur.

**Comment by matwho** [comment]
OK here it is the washer has just finished and looking at the LG app it says the machine has finished - please let me know if I can help get this sorted :)

[smartthinq_sensors-8c5c78f19178045b7dbcc8facd919e30-Front Load Washer-316795eaf002febc2fb3c685e9bb37e7.json-4.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8073693/smartthinq_sensors-8c5c78f19178045b7dbcc8facd919e30-Front.Load.Washer-316795eaf002febc2fb3c685e9bb37e7.json-4.txt)
.

**Comment by matwho** [comment]
Sorry it seems like it’s a bit random - I have run 4 more wash cycles twice it stops at 1 minute remaining and stays there untill the next cycle starts  The other two cycles it goes all the way to 0.

It would seem the best thing to do is reset the time remaining to 0 when sensor.front_load_washer_run_state goes to “Finished”.

On the 2 runs where the time remaining stays at 1 minute the sensor.front_load_washer_run_state also stays at “Finished”. On the other two runs it goes to “-“ a short time after cycle has actually finished. So you guess to would be good to correct that as well.

I guess the issue is with LG as both the runs when the time remaining stuck at 1 minute it was also somewhat erratic at when it updated the time remaining as the wash cycle was running.

Thanks for such a useful integration!

Matthew
