### ISSUE TITLE
Explanation of HVAC_ACTION being removed

### ISSUE THREAD

**Issue by wishie** [ollo69/ha-smartthinq-sensors#209]
**Describe the bug**
I am wondering why the 'HVAC_action' attribute has been removed?

**Expected behavior**
I expect the 'HVAC_action' attribute to be available.

```

```

Since 0.9.1 it seems 'hvac_action' attribute has been removed, with no (in my opinion) good reason. I have seen the ```Removed climate HVAC_ACTION to respect HA climate entity rules``` changelog entry, but find it strange that removing information is seen as a good thing. Especially when that extra information doesnt 'get in the way' or 'hurt' users who weren't/aren't using it anyway.

I've noticed a few integrations having to change things (usually not for the better) to fit in with some silly rules/specifications. I understand the need for consistency, and certain attributes should be mandatory for a device class, but **removing extra information** seems daft to me. Is there something I am missing?

**Comment by wishie** [comment]
Just did a quick search, and it seems there is no issue with HVAC_ACTION being allowed..

https://developers.home-assistant.io/docs/core/entity/climate/

**Comment by ollo69** [comment]
In Home Assistant HVAC_ACTION should represent "what device is doing" and should be used if is different from HVAC_MODE, for example the device mode is COOL  but the action is IDLE because target temperature is reached, then could change in action COOLING again when temperature go over target.
LG API do not allow to identify current action, so at the end HVAC_ACTION would be only a mirror of the HVAC_MODE, for this reason I removed this following HA dev guideline and because in my opinion it make sense.
So my question is: why you need this information if it is identical to HVAC_MODE?

**Comment by wishie** [comment]
The information isn't *identical* though, it's different ('cool' vs 'cooling' etc) and I was using it in automations. I am aware I could create a template etc to add this functionality back, but I see it as a bad move to provide less data. I think any data we can get from the LG API should be accessible to end users, as there is no telling what weird and wonderful things people can do with that data.

**Comment by ollo69** [comment]
> The information isn't _identical_ though, it's different ('cool' vs 'cooling' etc) and I was using it in automations

Just different word, not different device status. You can base your automation on HVAC_MODE and obtain identical results.

> I think any data we can get from the LG API should be accessible to end users

And that's what I try to do. But LG API do not provide information about HVAC_ACTION. But if one day this information will be available, I will be happy to manage it.

**Comment by ollo69** [comment]
Close this issue, thing that the question has been answered.
