### ISSUE TITLE
[BUG] Confusing refrigerator/freezer temperature control and sensors

### ISSUE THREAD

**Issue by ehn** [ollo69/ha-smartthinq-sensors#244]
**Describe the bug**
For a refrigerator/freezer, the controls and sensors make it look like the temperatures are measured, but they are not. They can only be set.

<img width="335" alt="Screen Shot 2021-11-25 at 19 25 05" src="https://user-images.githubusercontent.com/179446/143433158-1804ce48-b864-41ee-a9f7-7d809c505393.png">

All the available temperatures are what the thermostats are set to. For example, if I change the fridge temperature from 4ºC to 7ºC, the "Currently" field will also immediately change to 7ºC, regardless of the actual current temperature in the fridge.

This is the same in the LG ThinQ app and the rudimentary UI on the appliance, btw. The refrigerator/freezer certainly has temperature sensors, but it seems like LG hasn't bothered to make their output available to the end-user.

**Expected behavior**
Tbh, I'm not entirely sure how things should look/work, but the current presentation is confusing. Do other LG refrigerators/freezers provide the actual, measured temperature?

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant OS 6.6
 - Home Assistant version installed: 2021.11.5
 - Component version installed: v0.10.6
 - Last known working version: N/A
 - LG device type and model with issue: GS-X6011NS
 - LG devices connected (list): that refrigerator/freezer and a TV set

**Comment by ollo69** [comment]
As I know refrigerators do not return current temperature. Because the HA climate integration require current temperature, is set equal to target temperature. If you have an external sensor that can provide current temperature, you can integrate this using the `generic thermostat` integration.

**Comment by ehn** [comment]
Ok, that makes sense. I assume you've spent quite a bit of time thinking about this and that using a climate entity is the best way. Would it be possible to set the current temperature to something like "unknown" unless it's supplied by a different sensor?

**Comment by ollo69** [comment]
Do not set current temperature in climate integration should cause problem. I will take a look to this but I think that I cannot change it.

**Comment by davethetallguy** [comment]
Not that it helps with the data in the API, but LG proactively reached out to me about a potential issue with my freezer temperature. They were able to provide a graph of internal temperature over the previous 30 days. 

So it appears the refrigerator sends that information to LG, but LG does not provide it to the API. Unfortunate.

**Comment by ollo69** [comment]
You mean that they collect current temperature (and not only the set temperature)? It could be that in your freezer provide additional info that I'm not aware, maybe you could try enable debug for integration so that we can check the values in the payload.

**Comment by davethetallguy** [comment]
Yes, in late December the app notified me that my freezer temperature appeared to be warm (it was not a specific temperature.) Later I got a voicemail from the proactive care team. The agent sent me a graph of my temperature trends for December, which was higher on Christmas Day than any other day.  

Similarly several months ago I got a warning that the freezer door wasn't closed correctly. (On inspection I found ice build-up, so that alert was accurate.) The API doesn't seem to specify which door is open, so again there must be more data provided to LG.

That said, I ran the integration with debug on this afternoon. Unfortunately I don't see any details in the payload that would carry that additional data. 

A slightly redacted capture follows:

`2022-01-03 15:24:33 DEBUG (SyncWorker_3) [custom_components.smartthinq_sensors.wideq.core_v2] thinq2_get after: {'resultCode': '0000', 'result': {'langPackCommonVer': '123.7', 'langPackCommonUri': 'https://objectcontent.lgthinq.com/f25f0ed4-53d7-4136-bf1f-da89d210117f?hdnts=exp=1703997823~hmac=060c4071298678144a1f45b17a5975b19a5ec00aba30065009f4d75d2878ccd9', 'item': [{'appType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'US', 'modelName': '2REF11EII__M2', 'deviceType': 101, 'deviceCode': 'KI0102', 'alias': 'Refrigerator', 'deviceId': 'e1fe214f-be18-12c0-88fd-acf10881****', 'fwVer': '', 'imageFileName': 'home_appliances_img_fridge.png', 'imageUrl': 'https://objectcontent.lgthinq.com/af46bfb8-048b-4cb7-ab15-93ba970803f8?hdnts=exp=1701590413~hmac=ec5166729a0b4647578f3c34497ffb169cd954e6aa3b1048b336603daf734b17', 'smallImageUrl': 'https://objectcontent.lgthinq.com/de2f76ea-0b74-4ff9-9846-a9f56d6cf64d?hdnts=exp=1701590413~hmac=622ad57b30a7c13a53dd7bf376fce8c79cb0be6808ab8710254cf3b7f6a33d58', 'ssid': '*******', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'America/New_York', 'timezoneCodeAlias': 'USA/New_York', 'utcOffset': -5, 'utcOffsetDisplay': '-05:00', 'dstOffset': -4, 'dstOffsetDisplay': '-04:00', 'curOffset': -5, 'curOffsetDisplay': '-05:00', 'sdsGuide': '{"deviceCode":"KI01"}', 'newRegYn': 'N', 'remoteControlType': '', 'userNo': '**********', 'tftYn': 'N', 'modelJsonVer': 1.06, 'modelJsonUri': 'https://objectcontent.lgthinq.com/aa6380b5-dcf0-4cda-99b3-c8ce2cbb9491?hdnts=exp=1688108788~hmac=66e1f5b49a23eb324574aaf5cf2a01194fe7c240f96ec1e36be728ed760d19af', 'appModuleVer': 222.09, 'appModuleUri': 'https://objectcontent.lgthinq.com/75e0414f-1836-44bf-9ed6-604145b93216?hdnts=exp=1695880826~hmac=0499b82948ce9a657570c0a9f70a185d86eb35cf32b71eb01d026bca4951ce25', 'appRestartYn': 'Y', 'appModuleSize': 1563441, 'langPackProductTypeVer': 50.5, 'langPackProductTypeUri': 'https://objectcontent.lgthinq.com/ab612e2f-6bf6-495c-a9df-c488e9004981?hdnts=exp=1703832834~hmac=c3fb26e558e46d5d6993ce66468f69d1c1f9485d4c0acffb92c3128f72caf021', 'deviceState': 'E', 'snapshot': {'mid': 19461945.0, 'online': True, 'static': {'deviceType': '101', 'countryCode': 'US'}, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'Lrkj6iy1QUGFEp2HN36URg'}, 'refState': {'atLeastOneDoorOpen': 'CLOSE', 'freezerTemp': 8.0, 'fridgeTemp': 9.0, 'tempUnit': 'FAHRENHEIT', 'expressMode': 'OFF', 'freshAirFilter': 'AUTO', 'monStatus': 'NORMAL', 'smartSavingMode': 'SMARTGRID_DD_ON', 'waterFilter': '5_MONTH'}, 'timestamp': 1641249100963.0}, 'online': True, 'platformType': 'thinq2', 'area': 334505, 'regDt': 20220103130902.0, 'blackboxYn': 'Y', 'modelProtocol': 'STANDARD', 'order': 0, 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '01399F0B', 'partNumber': 'SAA41891901', 'order': 2.0}, {'checksum': '0000D658', 'partNumber': 'SAA41882401', 'order': 1.0}], 'modemInfo': {'modelName': '2REF11EII__M2', 'appVersion': 'clip_hna_v1.9.110', 'modemType': 'RTK_RTL8711am', 'ruleEngine': 'y'}, 'guideTypeYn': 'Y', 'guideType': 'TYPE1', 'regDtUtc': '20220103170902', 'regIndex': 0, 'groupableYn': 'N', 'controllableYn': 'N', 'combinedProductYn': 'N', 'masterYn': 'Y', 'pccModelYn': 'Y', 'sdsPid': {'sds4': '', 'sds3': '', 'sds2': '', 'sds1': ''}, 'autoOrderYn': 'N', 'initDevice': False, 'existsEntryPopup': 'N', 'tclcount': 0}], 'group': []}}`

**Comment by ollo69** [comment]
Unfortunately I have to agree with you, only target temperature available in this payload.
