### ISSUE TITLE
Add support for google accounts outside of the us

### ISSUE THREAD

**Issue by kiatchun** [ollo69/ha-smartthinq-sensors#280]
**Describe the solution you'd like**
Add google account support outside the US.

**Comment by ollo69** [comment]
Login with social network account in many case do not work properly and it is strongly suggested to use a dedicated LG account for this integration.
You can try to login with social network account using the `URL redirect login method` during setup, but if do not work or a specific method is not available this is not under my control.

I close this FR because there is nothing that I can do here.
