### ISSUE TITLE
Dehumidifier Fan Speed

### ISSUE THREAD

**Issue by NateGze** [ollo69/ha-smartthinq-sensors#403]
Please add support for control of dehumidifier fan speed. Thanks!

**Comment by ollo69** [comment]
I don't know exactly what you mean, but you need at least to add diagnostic so that I can check options provided by your device. Next time please use Feature request template to open a new Feature Request,

**Comment by NateGze** [comment]
I would like to control the fan speed through home assistant. There are two
speeds, low and high. They can be controlled through the LG app, but I
can’t see it could be done via your home assistant device now. Turning in
and off works, but I can’t see how the fan speed could be controlled.
Probably needs its own entity or something.

**Comment by ollo69** [comment]
Humidifier entity in HA do not support fan speed but only [modes](https://developers.home-assistant.io/docs/core/entity/humidifier#modes), that should be already be implemented. In any case please attach diagnostic so that I can check feature provided by your device and understand if something can be done.

**Comment by NateGze** [comment]
I see about the modes. Could I create two modes that are attached with changing the fan speed? The mode pulldown only offers “smart”.

**Comment by ollo69** [comment]
I will think about this, It could be an option create an associated fan device to manage this.

**Comment by NateGze** [comment]
Awesome, thanks.

**Comment by ollo69** [comment]
I did some tests for this. As final solution I choose to allow to set fan speed as mode for device like yours that only allow a single operation mode. I think that this should be address as feature request to HA, asking to add the fan option for humidifier entity, this should be the best solution. I also tried to use climate as entity for dehumidifier, but result is not so good because primary (and mandatory) attribute for climate entity is temperature that obviously has nothing to do with dehumidifier.
New implementation will be available on next days when I will publish new release.

**Comment by NateGze** [comment]
Happy new year! Thanks so much for looking into this and providing some
sort of solution. I look forward to seeing it in your next release. I
created a feature request for HA for this, feel free to upvote.

**Comment by ollo69** [comment]
New release is now available. Please test and give me your feed-back.

**Comment by NateGze** [comment]
Hi, thanks, it works. Much appreciated for your efforts. The one quirk I may have found is that if you change the mode before you turn it on, it doesn’t register. It is always responsive to mode changes when it has already been switched on though. Thanks again.

**Comment by ollo69** [comment]
I close this, if you have additional request please open new thread.
