### ISSUE TITLE
LG Airco: would it be possible to export attributes?

### ISSUE THREAD

**Issue by skinkie** [ollo69/ha-smartthinq-sensors#447]
**Is your feature request related to a problem? Please describe.**
The LG Airco ThinqQ app has attributes showing actual energy usage (kW) and total energy usage (kWh). In addition propreties like "AirPolution" (Sensor PM1, SensorPM2, SensorPM10). I would like to track these values per room.

**Describe the solution you'd like**
The ability to track (all) supported properties per device, preferably selectable in a similar fashion like happens with MQTT.

![image](https://user-images.githubusercontent.com/502394/209466367-2ede4d4d-ecb7-4d50-8559-9bd68bdcdcc7.png)

![image](https://user-images.githubusercontent.com/502394/209466350-8c7b2373-b063-4b7f-b69d-12b1bd403fca.png)

**Comment by ollo69** [comment]
I'm not understanding the meaning of this request, The way used to managed sensor inside HA is not something related to the integration but to HA itself and his architecture. If some sensors are missing open a specific FR attaching integration diagnostics so that I can check if available in payload and can be exposed in HA by integration.
