### ISSUE TITLE
LG Winecellar Support

### ISSUE THREAD

**Issue by hyunhobaek** [ollo69/ha-smartthinq-sensors#497]
I want to use the temperature and lighting features of the LG Wine Cellar.
I also want to know if the door is open.
Is this possible?

[config_entry-smartthinq_sensors-a3859ae7fa4f159de46da04de9a6bac7.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10731837/config_entry-smartthinq_sensors-a3859ae7fa4f159de46da04de9a6bac7.json.txt)

**Comment by ollo69** [comment]
This looks very similar to refrigerator (with less feature) and as I can see some information are available in payload, so your request can be implemented. This will take some times, because as you can see the list of FR is very long...
In the meantime please attach a LG app screenshot for this device so that I can have a more clear view of what kind of information are provided.

**Comment by hyunhobaek** [comment]
The LG app screenshot is in Korean, so I'm attaching the screenshot with Google Translate. Thank you.
![20230215_063047](https://user-images.githubusercontent.com/24352381/218868429-4f6c942e-be81-42fc-a891-e076d9c09b4d.jpg)

**Comment by ollo69** [comment]
Why you closed this?
