### ISSUE TITLE
Water Temperature sensor is showing some code

### ISSUE THREAD

**Issue by djcrawleravp** [ollo69/ha-smartthinq-sensors#571]
Sorry for not using the template for this, just that an image  is better

Water Temp sensor is showing this instead of "Warm"

<img width="489" alt="Screen Shot 2023-07-21 at 10 43 58" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/12896341/61899f12-c12d-4350-abcf-17c6e242a954">

**Comment by djcrawleravp** [comment]
Commenting just to prevent the “stale” label

**Comment by ollo69** [comment]
Pls attach device diagnostic

**Comment by djcrawleravp** [comment]
[config_entry-smartthinq_sensors-0d89da8c08b32a69cd8f2d4a90c145fd.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12526422/config_entry-smartthinq_sensors-0d89da8c08b32a69cd8f2d4a90c145fd.json.txt)


Exported Device Diagnostics from HA

**Comment by ollo69** [comment]
This label is not included in the translation file. I will further investigate this case, non sure I will be able to fix (eventually I should hard code this translation in a local file).
In meantime please provide the right translation as provided in LG app.
Please note that I will not be able to work on this before October because I'm working far from home this month, if issue become `stale` add a comment to avoid closure👍

**Comment by djcrawleravp** [comment]
Oh, I see, It is a translation issue?

WARM - CALIENTE
COLD - FRIA

This issue is just an observation, The integration is working flawlessly
