### ISSUE TITLE
Add Integration doesn't see smartthinq available

### ISSUE THREAD

**Issue by hspindel** [ollo69/ha-smartthinq-sensors#687]
Followed all the directions to install.  custom-components added to ~/homeassistant.  Verified files visible.

Rebooted homeassistant.  Shift/reloaded browser (Firefox).  Cleared cache for good measure.  Devices/Add Integration does not see smartthinq.  

Clues to what I'm doing wrong?

Thank you.

**Comment by ollo69** [comment]
I think that you are missing a `.` in your path. Configuration path should be `~/.homeassistant` 👍

**Comment by hspindel** [comment]
Thank you for the reply.

I did not originally have a .homeassistant directory, but there was a homeassistant directory, so I put the config files there.  I guess that was the wrong thing to do.

So I created a .homeassistant directory and put the config files there.  Now the problem is when I reboot home assistant the .homeassistant directory is gone.  

I am trying to run home assistant under VirtualBox.

I can restart home assistant from a VirtualBox restore point, and the .homeassistant directory reappears.  But the SmartThinQ LGE Sensors doesn't appear in the list of available integrations.

**Comment by ollo69** [comment]
There are a lot of possible reason for this that depend on your os / enviroment / etc.
If you are using Linux, just keep in mind 2 things:

1) file / directory in Linux that start with `.` are hidden
2) In Linux `~` means home directory, so the full path can be different and depend on the user you configure. If you create a user called `homeassistant` the full path should be something like `/usr/homeassistant/.homeassistant`.

I suggest to search more details on the ha forum / discord because your issue is not related to the integration but to ha configuration.

**Comment by hspindel** [comment]
The OS is HAOS running in a VirtualBox VM.

Yes, files starting with . are hidden but ls -al would show them.

I'm convinced this would work if I could get the files installed to the correct directory.  The instructions say to create custom_components in the same directory as configuration.yaml.  There is only one configuration.yaml file, and it is in /homeassistant.

Placing the custom_components file in /homeassistant and rebooting homeassistant does not result in  "SmartThinQ LGE Sensors" being available.

I regret that I have no access to discord.  Thank you for your answers.

**Comment by hspindel** [comment]
Never mind.  I tried installing with HACS instead of the manual menthod and got that to work.

Thank you for your help.

**Comment by ollo69** [comment]
Ok, I close this.
