### ISSUE TITLE
HVAC Status

### ISSUE THREAD

**Issue by josephny** [ollo69/ha-smartthinq-sensors#691]
I use an LG ducted heat pump with air handler system (several of them) and it would be very useful to know the current status of what the heat pump is doing.

For example, the system has modes such as HEAT, COOL, FAN, AUTO, OFF.

But, it would be nice to know if the system is being called to make heat or cool or air  -- and is doing so.

That is, for example, if the mode is HEAT, and the setpoint is above the room temperature, the heat pump should be making heat.  It would be helpful to track that.

Thank you.

**Comment by josephny** [comment]
Thank you.  Seems odd to me that they would not include it.

**Comment by ollo69** [comment]
I check again this because I understand that having the current action should be interesting, but LG AC device do not provide this information in the payload. I prefer to respect Home Assistant best practice that recommended to not add this information just as mirror of current HVAC mode (and by the way should be a problem determinate the action for device that support `auto` mode)
I close this FR for now.
