### ISSUE TITLE
LGE Devices Failed Setup, Will retry: ThinQ platform not ready

### ISSUE THREAD

**Issue by FarouqDin** [ollo69/ha-smartthinq-sensors#772]
**Describe the bug**
LGE Devices
Failed Setup, Will retry: ThinQ platform not ready

**Expected behavior**
several weeks i keep getting this bug

**Screenshots**
![Error Log LG 1](https://github.com/ollo69/ha-smartthinq-sensors/assets/163714984/5b06383b-50db-4608-a65c-265cac8e622f)
![Error Log LG 2](https://github.com/ollo69/ha-smartthinq-sensors/assets/163714984/d2041f2c-cc36-47bf-89c9-bfe71f125d2b)

**Environment details:**
Core - 2024.7.1
Supervisor- 2024.06.2
Operating System- 12.4
Frontend - 20240705.

 - LG device type - Washer and Dryer

**Output of HA logs**
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:269
integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 10:11:45 (1 occurrences)
Last logged: 10:11:45

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 269, in async_setup_entry
    client = await lge_auth.create_client_from_token(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 153, in create_client_from_token
    return await ClientAsync.from_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1605, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1513, in refresh
    self._auth = await self.auth.refresh(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 989, in refresh
    access_token, token_validity = await self._gateway.core.refresh_auth(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 707, in refresh_auth
    out = await self._auth_request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 675, in _auth_request
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError: Token Error

```

```

**Additional context**
looking at the error log, looks like token error, what i have read via this forum, something might be blocking. I have Deco Mesh system and use as router as well. Would be great if can get some assistance to get this up and running again.

**Comment by SpudsterZ** [comment]
Been having this same type of token error with my stove for quite some time now.

**Comment by createthisnl** [comment]
Same here since this morning with my washing machine. LG has changed something in the terms and conditions that I first had to accept in their LG TinQ app. After this was done, nothing changed. I tried to re-verify the integration (with the suggested repair button), but it didn't work. Then restart Home Assistant, also without success.

Then I added the integration again, without removing the old one (with this error message). Normally this is not possible, but if you now click the "Add Hub" (as shown on @FarouqDin second screenshot) button and log in again, this will bring the old hub back to life. That was the case with me.

Again, you don't have to delete anything. Simply click "Add Hub" on the integration details page and log in again. Be sure to first check the LG TinQ app for any changes to the general terms and conditions.

**Comment by jshatch** [comment]
I can't get it to reconnect at all.  Upon first trying it failed with invalid credentials, then I used the URL redirection method and that took me to a login page that accepted my creds but made me accept TOS and then forced me to rotate my password.  After doing that, it will login but finds no devices...

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/12240115/3538e136-404c-4d79-8dc2-45cfdb3207c3)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/12240115/8b8f8fdb-66dd-4552-9607-eb56ee4a493b)

Having MyQ flashbacks. :)

**Comment by tismofied** [comment]
This is has been my fix every time I see an issue with the integration for the last year. I immediately open the app on my phone, accept the terms and reload the integration.

**Comment by jchonig** [comment]
The disable/enable work around did not work for me.

Before disabling, I changed my password and accepted the new TOS in the app

I then tried the URL redirection link and at it took me back to the login page.  On the second try it posted "This URL not found".  Both on a desktop and mobile.

Now I'm in the `Failed to set up: ThinQ platform not ready` state with no options except disabling or deleting the integration.

**Comment by ollo69** [comment]
When LG change TOS is necessary to accept on LG app to be able to connect again with integration.
I understand that request to login again on integration confuse many user, I'll try to understand if there is a way to recognize the specific issue and eventually accept TOS without manual requests.

**Comment by nunoarias** [comment]
Even recreating the account it continues to gives the error "Failed Setup, Will retry: ThinQ platform not ready", I have tried delete integration, reboot HA, reload, etc. even recreate LG account

**Comment by DrShivang** [comment]
Same Issue here, trying since yesterday -- no workarounds are working
![image](https://github.com/user-attachments/assets/7c8a33c4-da37-40c1-a175-d918208c4e7d)

1. My Account Credentials are Email + Password based.
2. No New TOS was there to be accepted in the app.
3. It just stopped working with this error since yesterday.
4. I had to change the password as it was 29 months old (as it said).
5. I Changed the password via app when I tried to log back in & thereafter repeated the same step on the website (at login redirection URL) too just to be sure, so have changed/reset the password twice by now.
6. I noticed that the Website address being used by my LG ThinQ app is : https://in.lgemembers.com/lgacc/front/v1/home/retrieveHome (incase this points in some direction)

What's Working :
1. I can login via website (URL redirection and also login via LG Account as mentioned above).
2. I can use the ThinQ app, its working perfectly fine. I have tried logging out and logging back in to check if anything new comes up or new TOS.. nothing at all

Presently:
 Am getting this error while trying to log on HA (I have deleted the integration and now trying afresh after multiple failed attempts - still no luck)

![image](https://github.com/user-attachments/assets/dcae8d40-dafa-4ad9-a12e-569ee7937b10)

and this error while trying URL redirection method
![image](https://github.com/user-attachments/assets/737d5e18-a449-43ec-9df3-2171547a5b4c)

Need Help !

**Comment by createthisnl** [comment]
There are one or two checkboxes you can select whilst setting up the intergration. Try again with one of the checkboxes selected. I can't remember exactly what the values ​​were, but I thought you had something to do with use HTTP, which worked for me.

**Comment by adamf83** [comment]
I had this issue and finally pinned it down to Country Restrictions which part of my Unifi UDM-Pro.  Once that was disabled, it worked straight away so something about where this integration calls out to was being blocked because it's IP resolved to a country I was blocking. I then deleted it and tried again with it enabled and the first time it failed, the second time, it worked, so I suspect there are some URLs that are using some sort of geo routing.  A lot of it looks like AWS (I noticed references to ap-northeast-2 in the debug logs which is Seoul) so if you're blocking traffic to countries, this may be the cause for you.

**Comment by DrShivang** [comment]
> There are one or two checkboxes you can select whilst setting up the intergration. Try again with one of the checkboxes selected. I can't remember exactly what the values ​​were, but I thought you had something to do with use HTTP, which worked for me.

Tried that too, no luck there

**Comment by DrShivang** [comment]
> I had this issue and finally pinned it down to Country Restrictions which part of my Unifi UDM-Pro. Once that was disabled, it worked straight away so something about where this integration calls out to was being blocked because it's IP resolved to a country I was blocking. I then deleted it and tried again with it enabled and the first time it failed, the second time, it worked, so I suspect there are some URLs that are using some sort of geo routing. A lot of it looks like AWS (I noticed references to ap-northeast-2 in the debug logs which is Seoul) so if you're blocking traffic to countries, this may be the cause for you.

I can ping and open the URL too, verified that I can ping and access website. There's no blocking on IP in that manner.

**Comment by kalmma** [comment]
I still have the same problem, it seems that something is blocked in the home assistant installation.

If I do the same with the same login details in another Home assistant installation, it works fine.

What could this be?

**Comment by kalmma** [comment]
After searching for a year to find out what the problem is, I found it by chance yesterday somewhere in a forum.

The problem appeared to be caused by the country block to South Korea on my UDM.

After adjusting this, the devices came online in the add-on immediately.

**Comment by bajoseph04** [comment]
> Same here since this morning with my washing machine. LG has changed something in the terms and conditions that I first had to accept in their LG TinQ app. After this was done, nothing changed. I tried to re-verify the integration (with the suggested repair button), but it didn't work. Then restart Home Assistant, also without success.
> 
> Then I added the integration again, without removing the old one (with this error message). Normally this is not possible, but if you now click the "Add Hub" (as shown on [@FarouqDin](https://github.com/FarouqDin) second screenshot) button and log in again, this will bring the old hub back to life. That was the case with me.
> 
> Again, you don't have to delete anything. Simply click "Add Hub" on the integration details page and log in again. Be sure to first check the LG TinQ app for any changes to the general terms and conditions.

Thanks. This worked. I've been trying many options and even thought of a backup-restore of home assistant! But then didn't wanted to mess-up. Your solution was so simple but then I had spent hours before I reached this page!
