### ISSUE TITLE
Airco fan mode doesn't show auto but diffuse

### ISSUE THREAD

**Issue by sldewit** [ollo69/ha-smartthinq-sensors#812]
As can be seen in below screenshot the option for auto mode (which is currently selected in the app) is shown as "diffuse" in Home assistant. I guess this is some sort of mis-mapping of status. 
![image](https://github.com/user-attachments/assets/a84c6a97-9819-4d05-9dfd-70cef371dc75)

Also in the App I can only select low, medium and high speed. So not sure what LOW_MID and MID_HIGH will do.

**Comment by ollo69** [comment]
`Diffuse` is mapped to the mode `Nature` returned by device, the scope is to differentiate from the mode `Auto` returned by other devices. Because LG provide both mode in the list (`auto` and `diffuse`) I need to map the 2 modes in different mode. The other to modes are also returned by API, if they do nothing just ignore them.
