### ISSUE TITLE
LG Smartthinq HVAC: Ionizer unavailable 

### ISSUE THREAD

**Issue by XalaTheShepard** [ollo69/ha-smartthinq-sensors#821]
After a reboot of HA, the Ionizer buttons of both my HVAC became unavailable.
No update of the LG Smartthinq app has happened since the last time they were working.
I am running HA Core 2024.10.4 and the latest version of the LG Smartthinq custom component.
Could a change in the API have caused this issue?

Many thanks for looking into the issue.

For additional information, do not hesitate to contact me. 

Kind regards,

Robin

**Comment by dexternl** [comment]
I have 2 models of LG inverter airco's

**LG-H12MW**
This is the older model, currently waiting for a wifi module I ordered to link this one too.
This one has a buttons on remote:
**Plasma** this is the ionizer
**E/Saving**  This mode minimizes power consumption dur
ing cooling and increases the set temperature
 to the optimal level for a more comfortable en
vironment.
**A/Clean** In the cooling and dehumidifying operations,
 moisture is generated inside the indoor unit.
 Use the auto cleaning function to remove
 such moisture.
 
**LG-H09AP**
This one with wifi build in has buttons:
**Energy CTRL** similar to E/Saving above with has 80/60/40% modes
**FUNC** and **On**/**Off** buttons this allows you to set 4 modes that you can set on/off:
tree icon = ionizer/plasma
fan icon = reduce outdoor unit noise
LH = freeze protect
airco icon = same as A/Clean above.

I don't know why the A/Clean isn't always on, since when cooling in summer it can actually make your airco drip water on the inside when off.

The other features are really nice. When the device is off, you can just push the plasma or func set plasma and the airco will basically just be a air purifier and only drain like 15~25watt while it only cleans your air.

I do fear that these are not available to be implemented in home assistant. Since when I look in the LG ThinQ app the only one available is the LH freeze protect. 

But yeah if these modes could be added to home assistant what would be great!
